### ISSUE TITLE
getec2suggestions generate an error

### ISSUE THREAD

**Issue by Mor-Walkme** [gregoryjordanm/awsrightsizer#6]
Hey,
When i try to run it, i get the following error:
ERROR:modules:General Exception
Traceback (most recent call last):
  File "/home/mor.h/git/awsrightsizer/modules/classes.py", line 855, in getec2suggestions
    'App': f'{appId}',
UnboundLocalError: local variable 'appId' referenced before assignment

Please advise.

Thanks,
Mor.

**Comment by ghost** [comment]
can do you a ```git pull``` and ```git checkout develop``` and see if that fixed your issue. I will merge it after if so.

**Comment by Mor-Walkme** [comment]
Thanks, i am still facing the same issue:
python3.6 rightsizer.py -k XXXX -s XXXX-r eu-central-1
ERROR:modules:General Exception
Traceback (most recent call last):
  File "/home/mor.h/git/awsrightsizer/modules/classes.py", line 855, in getec2suggestions
    'App': f"{appId or 'Unavailable'}",
UnboundLocalError: local variable 'appId' referenced before assignment
ERROR:modules:General Exception
Traceback (most recent call last):
  File "/home/mor.h/git/awsrightsizer/modules/classes.py", line 855, in getec2suggestions
    'App': f"{appId or 'Unavailable'}",
UnboundLocalError: local variable 'appId' referenced before assignment
ERROR:modules:General Exception
Traceback (most recent call last):
  File "/home/mor.h/git/awsrightsizer/modules/classes.py", line 855, in getec2suggestions
    'App': f"{appId or 'Unavailable'}",
UnboundLocalError: local variable 'appId' referenced before assignment

**Comment by ghost** [comment]
Ok, I have removed the referenced to AppId all-together, do another ```git pull``` and ```git checkout develop``` and try one more time for me

**Comment by Mor-Walkme** [comment]
Thanks, now it has generated a bit different error after some time:
python3.6 rightsizer.py -k XXXX -s XXXX-r eu-central-1
ERROR:modules:General Exception
Traceback (most recent call last):
  File "/home/mor.h/git/awsrightsizer/modules/classes.py", line 1188, in getrdssuggestions
    'Name': f'{instanceName}',
NameError: name 'instanceName' is not defined
ERROR:modules:General Exception
Traceback (most recent call last):
  File "/home/mor.h/git/awsrightsizer/modules/classes.py", line 1188, in getrdssuggestions
    'Name': f'{instanceName}',
NameError: name 'instanceName' is not defined

**Comment by ghost** [comment]
Ok, I fixed the missing definition. Try the pull and checkout one more time.

**Comment by Mor-Walkme** [comment]
Now it works just fine. thanks for your help.
